// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv

import { defineConfig } from "@prisma/config";
import "dotenv/config";

export default defineConfig({
  schema: 'prisma/schema.prisma',
  datasourceUrl: process.env.DATABASE_URL,
  seed: "npx tsx prisma/seed.ts",
});
