import { CaseStudy } from "./caseStudy.types";

export const caseStudiesData: CaseStudy[] = [
  {
    id: "finpay-innovators",
    title: "FinPay Innovators: 30-Day Fast-Track Registration & DPIIT Recognition",
    category: "Startup Registration",
    industry: "FinTech",
    location: "Bangalore, KA",
    excerpt: "Navigating complex multi-director documentation and regulatory clearances to achieve Startup India recognition in record time.",
    challenge: "FinPay Innovators was building a payment gateway solution. They needed to qualify for the DPIIT certificate to secure capital gains tax exemptions and intellectual property fast-tracking. However, their internal registration attempts stalled due to intricate compliance clauses in their memorandum of association (MoA) and query responses required by corporate registry offices.",
    solution: "Arambh Advisory took over the registration process. We first restructured their MoA to fit startup qualification standards, then managed the complete application flow through the Startup India portal. We drafted a detailed innovation pitch deck explaining their proprietary API and handled direct queries from government assessors.",
    result: "Secured formal DPIIT registration in exactly 28 days. This allowed the startup to unlock patent application fast-tracking (80% rebate) and establish their trust accounts without standard bureaucratic delay.",
    metrics: "28-Day Approval",
    image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "mediconnect-grants",
    title: "MediConnect: Securing ₹2Cr in Government Funding & Grants",
    category: "Funding Support",
    industry: "HealthTech",
    location: "Pune, MH",
    excerpt: "Preparing complex financial models, project proposals, and pitch decks to qualify for national healthcare technology grants.",
    challenge: "MediConnect developed an AI-based rural diagnostic device. While their technology was sound, they lacked the specialized documentation, financial projections, and compliance audits required to pitch for high-value government grants like the Startup India Seed Fund Scheme (SISFS) and biotechnology grants.",
    solution: "Our advisory team restructured their financial models to show transparent unit economics and projected developmental impact in rural clinics. We compiled their technical audit reports and designed a compliance-optimized project report tailored to the evaluation committee's scoring parameters.",
    result: "Successfully presented and secured a total of ₹2 Crore under the seed fund and technology development programs, with the initial tranche disbursed within 45 days.",
    metrics: "₹2Cr Funding Secured",
    image: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "agrigrow-compliance",
    title: "AgriGrow: Streamlining Multi-State Compliance & Tax Restructuring",
    category: "Compliance & Advisory",
    industry: "AgriTech",
    location: "Nashik, MH",
    excerpt: "Optimizing supply chain contracts, state tax filings, and MSME interest subsidies to boost cash flow by 35%.",
    challenge: "AgriGrow was expanding its cold chain logistics across Maharashtra, Gujarat, and Madhya Pradesh. Managing decentralized state registrations, labor laws, and seasonal tax filings led to late compliance penalties and frozen credit balances.",
    solution: "Arambh Advisory consolidated their multi-state tax structure, set up a centralized compliance dashboard, and applied for MSME credit schemes.",
    result: "Resolved all pending state audit flags and established monthly reporting schedules, reducing compliance risk to zero.",
    metrics: "35% Cash Flow Boost",
    image: "https://images.unsplash.com/photo-1595974482597-4b8da8879bc5?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "ecocharge-subsidy",
    title: "EcoCharge: Navigating Subsidy Audits & Green Tech MSME Benefits",
    category: "MSME Benefits",
    industry: "CleanTech",
    location: "Ahmedabad, GJ",
    excerpt: "Unlocking collateral-free loans and state electricity duty exemptions for an expanding electric vehicle charging network.",
    challenge: "EcoCharge was scaling its network of charging stations but faced heavy initial capital requirements. They were unaware of specific state-level green energy subsidies and capital rebates available to MSMEs.",
    solution: "We registered EcoCharge under the MSME category, structured their project reports for the CGTMSE loan scheme (collateral-free), and submitted claims for local electricity duty exemptions.",
    result: "Secured ₹1.5 Crore collateral-free working capital loan and saved 15% in operational utility costs through green energy exemptions.",
    metrics: "₹1.5Cr Collateral Loan",
    image: "https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "shopkart-restructuring",
    title: "ShopKART: Converting Sole Proprietorship to Private Limited with Multi-Founder Equity",
    category: "Startup Registration",
    industry: "E-commerce",
    location: "Mumbai, MH",
    excerpt: "Structuring co-founder shares, intellectual property transfers, and initial GST registrations for an online retail brand.",
    challenge: "The founder of ShopKART wanted to bring on co-founders and raise external capital, but the business was registered as a sole proprietorship, making equity distribution and outside investment legally impossible.",
    solution: "Arambh Advisory structured their corporate migration, incorporating them as a Private Limited company, drafting a robust Shareholder Agreement (SHA), and filing their new GST registrations.",
    result: "Successfully migrated all assets and IP to the new entity within 15 days, allowing the founders to close their first angel check immediately.",
    metrics: "Seamless Restructuring",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "learncore-governance",
    title: "LearnCore: Restructuring Corporate Governance for Series-A Readiness",
    category: "Business Consulting",
    industry: "EdTech",
    location: "Gurgaon, HR",
    excerpt: "Conducting diagnostic compliance audits and cleaning up shareholder cap tables to prepare for venture capital investment.",
    challenge: "LearnCore had a term sheet from a major VC firm, but the investor's due diligence team flagged unfiled corporate returns, disorganized board minutes, and a messy cap table involving early freelance advisers.",
    solution: "Arambh Advisory conducted an intensive 3-week compliance cleanup, formalizing all historical board resolutions, correcting past filings, and structuring legal buyouts for early equity agreements.",
    result: "Cleared the due diligence report with zero critical flags, enabling the startup to close their Series-A funding on schedule.",
    metrics: "Series-A Compliant",
    image: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "logiroute-loans",
    title: "LogiRoute: Unlocking ₹75L Subsidized Loans via Udyam Benefits",
    category: "MSME Benefits",
    industry: "Logistics",
    location: "Chennai, TN",
    excerpt: "Leveraging Udyam MSME status to secure lower interest rates and priority sector lending facilities for fleet expansion.",
    challenge: "LogiRoute needed to acquire 15 new delivery vans to fulfill a contract, but commercial vehicle interest rates from major banks were close to 13%, making the expansion financially unsustainable.",
    solution: "We registered LogiRoute under the Udyam portal, verified their eligibility for interest subvention schemes, and applied to priority sector lending departments.",
    result: "Secured fleet financing at a subsidized rate of 8.25%, saving the company over ₹12 Lakhs in interest payments over the loan tenure.",
    metrics: "4.75% Interest Savings",
    image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "cloudpos-crossborder",
    title: "CloudPOS: Setting Up Compliant Cross-Border SaaS Billing Structures",
    category: "Compliance & Advisory",
    industry: "SaaS",
    location: "Hyderabad, TS",
    excerpt: "Establishing GST export procedures, transfer pricing compliance, and double-taxation relief strategies for global customers.",
    challenge: "CloudPOS was selling software subscriptions to clients in the US and Europe. They were facing issues with international payment compliance, double taxation on service exports, and unoptimized GST refund filings.",
    solution: "Arambh Advisory designed a compliant export invoicing workflow, filed their Letter of Undertaking (LUT) for zero-rated GST exports, and set up transfer pricing documentation.",
    result: "Unlocked monthly GST refunds on input tax credits and ensured 100% compliance with international billing guidelines.",
    metrics: "100% Tax Compliant",
    image: "https://images.unsplash.com/photo-1551434678-e076c223a692?auto=format&fit=crop&w=800&q=80",
  }
];
